server:
  port: 8080

logging:
  level:
    com.example: DEBUG

spring:
  application:
    name: retry-config
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example"
    listener:
      ack-mode: MANUAL_IMMEDIATE
    producer:      
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 20
        batch.size: 65536
        compression.type: lz4